.gitignore
.storybook/main.ts
.storybook/preview.tsx
package.json
pnpm-lock.yaml
tsconfig.app.json

[PREAM-92] 스토리북 세팅
close #3 
- 디자인 시스템 컴포넌트에 대한 테스트를 진행하기 위해 스토리북 세팅 작업을 진행했습니다.
- 컴포넌트를 만들 때 화면과 독립적으로 개발하기 위한 환경이 필요했습니다!
[PREAM-92]: https://team-pream.atlassian.net/browse/PREAM-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-92] 스토리북 세팅

---

src/components/text/index.stories.ts
src/components/text/index.tsx
src/styles/typography.ts

[PREAM-95] 텍스트 컴포넌트 추가
close #9 
- 텍스트 컴포넌트를 추가했습니다.
- 아래와 같은 형식으로 편리하게 사용할 수 있습니다!
```javascript
<Text typo="title1" color={colors.gray400}/>
```
- 디자인 시스템을 편리하게 적용할 수 있습니다!
[PREAM-95]: https://team-pream.atlassian.net/browse/PREAM-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-95] 텍스트 컴포넌트 추가

---

.storybook/preview.tsx
src/components/gnb/index.stories.ts
src/components/gnb/index.styles.ts
src/components/gnb/index.tsx
src/constants/routes.ts
src/styles/theme.ts

[PREAM-29] GNB 컴포넌트 추가
close #11 
- GNB(Global Navigation Bar) 컴포넌트를 추가했습니다.
- 공통 UI 컴포넌트 (디자인 시스템) 개발이 필요합니다.
[PREAM-29]: https://team-pream.atlassian.net/browse/PREAM-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-29] GNB 컴포넌트 추가

---

src/api/categories/index.ts
src/api/category/index.ts
src/pages/main/index.styles.ts
src/pages/main/index.tsx
src/queries/categories/index.ts
src/queries/query-keys.ts

[PREAM-87] 메인페이지 카테고리 UI 구현 및 라우터 연결
close #7 
- 카테고리 UI 구현
- 라우트 기능 구현
[PREAM-87]: https://team-pream.atlassian.net/browse/PREAM-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-87] 메인페이지 카테고리 UI 구현 및 라우터 연결

---

src/App.tsx
src/api/category/index.ts
src/pages/category/components/category-item.tsx
src/pages/category/components/category-item/index.styles.ts
src/pages/category/components/category-item/index.tsx
src/pages/category/index.styles.ts
src/pages/category/index.tsx
src/pages/index.ts
src/queries/category/index.ts
src/queries/query-keys.ts

[PREAM-33] 카테고리 페이지 개발
close #13
카테고리 페이지를 UI를 구현했습니다.
카테고리 조회 api를 연동하였습니다.
[PREAM-33]: https://team-pream.atlassian.net/browse/PREAM-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-33] 카테고리 페이지 개발

---

src/components/button/index.stories.ts
src/components/button/index.styles.ts
src/components/button/index.tsx
src/styles/colors.ts

[PREAM-30] 버튼 컴포넌트 개발
resolve #20 
- 디자인 시스템에 있는 버튼 컴포넌트를 구현했습니다.
- 아래처럼 간편하게 버튼을 사용할 수 있습니다.
```javascript
<Button variant="box" size="xl" status="disabled">프림</Button>
```
[PREAM-30]: https://team-pream.atlassian.net/browse/PREAM-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-30] 버튼 컴포넌트 개발

---

src/App.tsx
src/api/category/index.ts
src/pages/category/components/category-item/index.styles.ts
src/pages/category/components/category-item/index.tsx
src/pages/category/index.styles.ts
src/pages/category/index.tsx
src/pages/index.ts
src/queries/category/index.ts
src/queries/query-keys.ts

* feat: 카테고리 페이지 조회 기능
* refactor: 카테고리 컴포넌트 파일 분류
* fix: 디자인 수정
* fix: api 수정
* refactor: 코드 리팩토링
[PREAM-23] 카테고리 페이지에서 카테고리를 확인할 수 있다
close #18
- 카테고리 페이지를 개발했습니다.
[PREAM-23]: https://team-pream.atlassian.net/browse/PREAM-23?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-23] 카테고리 페이지에서 카테고리를 확인할 수 있다

---

.storybook/preview.tsx
src/components/search-bar/index.stories.ts
src/components/search-bar/index.styles.ts
src/components/search-bar/index.tsx
src/styles/global-style.tsx

[PREAM-100] Search bar 컴포넌트 구현
close #22 
- Search bar 컴포넌트를 구현했습니다.
- Search bar 컴포넌트를 구현했습니다.
[PREAM-100]: https://team-pream.atlassian.net/browse/PREAM-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-100] Search bar 컴포넌트 구현

---

.github/workflows/deploy-storybook.yml
.gitignore
README.md
package.json
pnpm-lock.yaml

Storybook 배포를 위한 workflow 작성
close #34 
- Storybook 배포를 위한 github actions workflow를 작성했습니다.
- 디자인 시스템 컴포넌트를 스토리북을 통해 간편하게 확인하고 테스트 할 수 있습니다.
- develop 브랜치에 새로운 커밋이 push될 경우 storybook을 자동 배포합니다.

[PREAM-94] Storybook 배포를 위한 workflow 작성

---

.github/workflows/deploy-storybook.yml
src/App.tsx
src/api/api.ts
src/api/category/index.ts
src/api/index.ts
src/components/app-bar/index.styles.ts
src/components/app-bar/index.tsx
src/components/button/index.styles.ts
src/components/fab/index.styles.ts
src/components/gnb/index.styles.ts
src/components/gnb/index.tsx
src/components/index.ts
src/pages/auth/index.tsx
src/pages/auth/pages/kakao-callback/index.tsx
src/pages/category/components/category-item/index.styles.ts
src/pages/category/components/category-item/index.tsx
src/pages/category/index.styles.ts
src/pages/category/index.tsx
src/pages/index.ts
src/pages/login/index.styles.ts
src/pages/login/index.tsx
src/queries/category/index.ts
tsconfig.app.json

[PREAM-108] 공통 UI 컴포넌트 적용
close #37 
- 구현이 완료된 페이지에 대해 공통 UI 컴포넌트를 적용했습니다.
- Storybook 배포 workflow를 수정했습니다.
- 페이지 폴더 구조를 변경했습니다.
- 디자인 시스템 컴포넌트 적용으로 일관된 디자인을 제공하고, 개발자 입장에서도 편리하게 사용할 수 있습니다.
[PREAM-108]: https://team-pream.atlassian.net/browse/PREAM-108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-108] 공통 UI 컴포넌트 적용

---

src/App.tsx
src/pages/index.ts
src/pages/products/index.styles.ts
src/pages/products/index.tsx

[PREAM-35] 상품 목록 페이지 화면 개발
close #39
- 상품 목록 페이지 화면 개발을 했습니다.
- 상품 목록 페이지 UI를 구현했습니다.
[PREAM-35]: https://team-pream.atlassian.net/browse/PREAM-35?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-35] 상품 목록 페이지 화면 개발

---

src/components/button/index.styles.ts
src/components/input/index.stories.tsx
src/components/input/index.styles.ts
src/components/input/index.tsx
src/components/search-bar/index.styles.ts
src/components/text/index.tsx
src/styles/typography.ts

[PREAM-117] Input 컴포넌트에 하단 컨펌 메시지 추가
close #45 
- Input 컴포넌트에 하단 컨펌 메시지를 추가했습니다.
- Input 컴포넌트에 하단 컨펌 메시지를 추가했습니다.
[PREAM-117]: https://team-pream.atlassian.net/browse/PREAM-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-117] Input 컴포넌트에 하단 컨펌 메시지 추가

---

src/constants/routes.ts
src/pages/auth/pages/kakao-callback/index.tsx

[PREAM-97] 페이지 경로 상수화
close #43 
- 페이지별 경로를 `ROUTE_PATHS` 라는 상수로 관리합니다.
- 페이지 경로가 변경될 경우, 전체를 바꿔야 하는 문제를 해결했습니다.
- 멘토님과 코치님의 피드백을 바탕으로 설계했습니다!
[PREAM-97]: https://team-pream.atlassian.net/browse/PREAM-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-97] 페이지별 경로 상수화

---

src/components/button/index.stories.ts
src/components/button/index.styles.ts
src/components/button/index.tsx
src/components/dialog/index.stories.ts
src/components/dialog/index.styles.ts
src/components/dialog/index.tsx
src/components/index.ts
src/components/input/index.stories.tsx
src/components/input/index.styles.ts
src/components/input/index.tsx
src/styles/colors.ts
src/styles/theme.ts

[PREAM-118] Dialog 컴포넌트 추가
close #47 
- Dialog 컴포넌트를 추가했습니다.
- Dialog를 사용할 수 있습니다.
- 만약 에러 표시를 위해 사용한다면 아래처럼 작성해 주세요.
```javascript
<Dialog type="error" title="상품 조회 실패" description="상품 정보를 불러오는 데 실패했어요." primaryActionLabel="다시 시도하기"/>
```
[PREAM-118]: https://team-pream.atlassian.net/browse/PREAM-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-118] Dialog 컴포넌트 추가

---

src/components/button/index.styles.ts
src/components/button/index.tsx
src/components/chip/index.stories.ts
src/components/chip/index.styles.ts
src/components/chip/index.tsx
src/components/chip/radio-group/index.stories.tsx
src/components/chip/radio-group/index.styles.ts
src/components/chip/radio-group/index.tsx
src/components/dialog/index.tsx
src/components/fab/index.tsx
src/components/index.ts
src/components/input/index.stories.tsx
src/components/input/index.tsx
src/components/radio-group/index.stories.tsx
src/components/radio-group/index.styles.ts
src/components/radio-group/index.tsx
src/components/search-bar/index.tsx
src/components/text/index.tsx

[PREAM-133] 라디오 그룹 컴포넌트 추가
#64 
- 판매 등록 페이지에 필요한 UI 컴포넌트를 추가했습니다.
- Radio group 컴포넌트를 수정했습니다.
- Chip radio group 컴포넌트를 추가했습니다.
- Button 컴포넌트에서 `variant`를 `shape`로 변경했습니다.
- 판매 등록 페이지에 필요한 UI 컴포넌트를 추가했습니다.
[PREAM-133]: https://team-pream.atlassian.net/browse/PREAM-133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-133] 라디오 그룹 컴포넌트 추가

---

src/assets/icons/AppBarBack.tsx

[PREAM-146] 파일명 대소문자 구분
close #91 
- 대소문자 구분이 안 되어 있는 컴포넌트가 존재하여 변경했습니다.
- 대소문자 구분이 안 되어 있는 컴포넌트가 존재하여 스토리북이 빌드되지 않았습니다.
[PREAM-146]: https://team-pream.atlassian.net/browse/PREAM-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-146] 파일명 대소문자 구분

---

src/pages/orders/pages/complete/index.styles.ts
src/pages/orders/pages/complete/index.tsx

[PREAM-141] 구매완료 화면 구현
close #94 
- 구매완료 페이지 UI 개발
- 구매에 성공했을 시 보여지는 구매완료 페이지 UI를 구현하였습니다.
[PREAM-141]: https://team-pream.atlassian.net/browse/PREAM-141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-141] 구매완료 화면 구현

---

src/api/products/index.ts
src/pages/mypage/pages/sales-list/index.style.ts
src/pages/mypage/pages/sales-list/index.tsx
src/queries/products/index.ts
src/queries/query-keys.ts
src/types/products/index.ts

[PREAM-81] 판매내역 페이지 개발 완료
close #84 
- 판매 내역 페이지 UI를 구현했습니다
- 판매 내역 페이지 api를 연동했습니다
[PREAM-81]: https://team-pream.atlassian.net/browse/PREAM-81?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-81] 판매내역 페이지 개발 완료

---

.gitignore
.svgrrc.cjs
src/assets/icons/AppBarBack.tsx
src/assets/icons/AppbarBack.tsx
src/assets/icons/Complete.tsx
src/assets/icons/DropdownFold.tsx
src/assets/icons/DropdownUnfold.tsx
src/assets/icons/EmotionalPetIcon.tsx
src/assets/icons/FabPlus.tsx
src/assets/icons/GnbCategory.tsx
src/assets/icons/GnbHome.tsx
src/assets/icons/GnbMy.tsx
src/assets/icons/KakaoLogo.tsx
src/assets/icons/LikeOff.tsx
src/assets/icons/LikeOn.tsx
src/assets/icons/Logo.tsx
src/assets/icons/MypageUploadImage.tsx
src/assets/icons/ProductsDetailOption.tsx
src/assets/icons/Search.tsx
src/assets/icons/SelectCat.tsx
src/assets/icons/SelectDog.tsx
src/assets/icons/UploadPlus.tsx
src/components/action-sheet/index.stories.ts
src/components/chip/radio-group/index.stories.tsx
src/pages/mypage/pages/address/components/addAddress/index.tsx
src/pages/orders/pages/order/components/shipping-info/index.tsx
src/pages/orders/pages/order/hooks/use-search-address.ts
src/pages/products/pages/upload/index.tsx

[PREAM-168] 빌드 에러 해결
close #136 
- 사용하지 않는 변수 제거
- 잘못 사용된 필드명 변경
- 빌드 에러 해결
[PREAM-168]: https://team-pream.atlassian.net/browse/PREAM-168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-168] 빌드 에러 해결

---

src/pages/products/pages/detail/components/product-info/index.tsx
src/pages/products/pages/detail/index.tsx
src/pages/products/pages/detail/types/index.ts
src/pages/products/pages/detail/utils/index.ts

[PREAM-166]
close #
- 제품 상세 페이지의 `condition`을 나타냅니다.
- 시간 format을 생성해서 업로드한 날짜를 나타냅니다.
[PREAM-166]: https://team-pream.atlassian.net/browse/PREAM-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-166] 제품상세의 시간, 상태 반

---

src/pages/products/pages/detail/components/product-info/index.tsx
src/pages/products/pages/detail/index.tsx
src/pages/products/pages/detail/types/index.ts
src/pages/products/pages/detail/utils/index.ts

[PREAM-166] 제품상세의 시간, 상태 반영
develop 머지용 PR입니다!
[PREAM-166]: https://team-pream.atlassian.net/browse/PREAM-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-166] 제품상세의 시간, 상태 반영

---

pnpm-lock.yaml
src/api/users/index.ts
src/components/action-sheet/index.styles.ts
src/pages/mypage/pages/main/index.styles.ts
src/pages/mypage/pages/main/index.tsx
src/pages/mypage/pages/pet-profile/index.tsx
src/pages/mypage/pages/user-profile/index.styles.ts
src/pages/mypage/pages/user-profile/index.tsx
src/pages/products/index.tsx
src/queries/users/index.ts
src/types/users/index.ts

[PREAM-165]
close #130 
- 마이페이지 사용자/반려동물 등록/수정 시 유효성 검사 기능 추가
- 마이페이지 디자인 수정
- 코드에서 빨간 줄 뜨는 부분 해결
-
-
[PREAM-165]: https://team-pream.atlassian.net/browse/PREAM-165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-165] 유효성검사 확인

---

src/pages/products/pages/list/index.tsx

[PREAM-164] 카테고리 이름 수정
close #150 
- 카테고리 이름이 undefined 되는 현상을 수정하였습니다.
[PREAM-164]: https://team-pream.atlassian.net/browse/PREAM-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-164] 카테고리 이름 수정

---

src/pages/onboarding/components/pet-type/index.styles.ts

[PREAM-145] 반려동물 타입 선택 시 글자 색 변경
close #156 
- 반려동물 타입 선택 시 글자 색을 변경되도록 하였습니다. (테두리 색으로 통일했습니다.)
[PREAM-145]: https://team-pream.atlassian.net/browse/PREAM-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-145] 반려동물 타입 선택 시 글자 색 변경

---

package.json
pnpm-lock.yaml
src/pages/main/components/category-list/index.tsx
src/pages/main/components/category-list/indexSkeleton.tsx
src/pages/main/components/product-list/index.tsx
src/pages/main/components/product-list/indexSkeleton.tsx
src/pages/main/index.tsx
src/pages/mypage/pages/main/index.styles.ts
src/pages/products/pages/detail/components/product-info/index.style.ts
src/pages/products/pages/detail/components/product-info/indexSkeleton.tsx
src/pages/products/pages/detail/index.tsx
src/pages/products/pages/list/indexSkeleton.tsx

[PREAM-153] 스켈레톤 UI 구현
close #124 
- 메인페이지 스켈레톤 UI 적용
- 상세정보페이지 스켈레톤 UI 적용
- 상품 목록 페이지 로더 적용
- 카테고리 페이지 스켈레톤 UI 적용
[PREAM-153]: https://team-pream.atlassian.net/browse/PREAM-153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-153] 스켈레톤 UI 구현

---

pnpm-lock.yaml
src/api/api.ts
src/pages/mypage/pages/address/components/addAddress/index.tsx
src/pages/mypage/pages/address/components/address-form/components/map/index.tsx
src/pages/mypage/pages/address/components/address-form/index.tsx
src/pages/onboarding/index.tsx

[PREAM-181] 프론트 빌드 에러 수정
[PREAM-181] 프론트 빌드 에러 수정
프론트 빌드 에러 수정
[PREAM-181]: https://team-pream.atlassian.net/browse/PREAM-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PREAM-181]: https://team-pream.atlassian.net/browse/PREAM-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-181] 프론트 빌드 에러 수정

---

src/pages/mypage/pages/address/components/address-form/components/map/index.tsx
src/pages/mypage/pages/address/components/address-form/index.tsx
src/pages/orders/pages/checkout/index.tsx

[PREAM-181] 에러 사항 수정
[PREAM-181] 에러 사항 수정
로그인 안했을 때 구매하기 버튼 누르면 발생 수정
[PREAM-181]: https://team-pream.atlassian.net/browse/PREAM-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PREAM-181]: https://team-pream.atlassian.net/browse/PREAM-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PREAM-181] 에러 사항 수정
